// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.EntityFramework;

namespace Project.EntityFramework.Migrations
{
    [DbContext(typeof(Food_deliveryDbContext))]
    [Migration("20210510125458_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Food_delivery.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("amount_of_orders")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Food_delivery.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("customerid")
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("target_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("customerid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Food_delivery.Models.Order", b =>
                {
                    b.HasOne("Food_delivery.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerid");

                    b.OwnsOne("Food_delivery.Models.Delivery", "delivery", b1 =>
                        {
                            b1.Property<int>("Orderid")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("avg_deliv_cost")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("avg_deliv_time")
                                .HasColumnType("int");

                            b1.Property<string>("main_restaurant")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("phone_number")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("time_of_work")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Orderid");

                            b1.ToTable("Deliveries");

                            b1.WithOwner()
                                .HasForeignKey("Orderid");
                        });

                    b.OwnsOne("Food_delivery.Models.Product", "product", b1 =>
                        {
                            b1.Property<int>("Orderid")
                                .HasColumnType("int");

                            b1.Property<int>("amount_avail")
                                .HasColumnType("int");

                            b1.Property<string>("avg_score")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("delivery")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("dish")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("price")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Orderid");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("Orderid");
                        });

                    b.Navigation("customer");

                    b.Navigation("delivery");

                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
